services:
  nestjs:
    build: .
    container_name: app
    ports:
      - "${PORT}:3030"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=${DB_URI}
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  react:
    build:
      dockerfile: Dockerfile.portal
    container_name: react-app
    ports:
      - "3000:3000"  # Map port 80 in the container to port 3000 on your host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data:
